// <auto-generated />
using FEZAutoScore.Model.Entity;
using FEZAutoScore.Model.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FEZAutoScore.Migrations
{
    [DbContext(typeof(ScoreRepository))]
    [Migration("20180119161212_AddWarSideColumn")]
    partial class AddWarSideColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("FEZAutoScore.Model.Entity.ScoreEntity", b =>
                {
                    b.Property<DateTime>("記録日時");

                    b.Property<string>("Map名")
                        .IsRequired();

                    b.Property<int>("PC与ダメージ");

                    b.Property<int>("キルダメージボーナス");

                    b.Property<int>("キル数");

                    b.Property<int>("クリスタル採掘量");

                    b.Property<int>("クリスタル運用ボーナス");

                    b.Property<string>("スキル1")
                        .IsRequired();

                    b.Property<string>("スキル2")
                        .IsRequired();

                    b.Property<string>("スキル3")
                        .IsRequired();

                    b.Property<string>("スキル4")
                        .IsRequired();

                    b.Property<string>("スキル5")
                        .IsRequired();

                    b.Property<string>("スキル6")
                        .IsRequired();

                    b.Property<string>("スキル7")
                        .IsRequired();

                    b.Property<string>("スキル8")
                        .IsRequired();

                    b.Property<int>("デッド数");

                    b.Property<string>("備考");

                    b.Property<int>("召喚行動ボーナス");

                    b.Property<int>("召喚解除ボーナス");

                    b.Property<int>("建築与ダメージ");

                    b.Property<int>("建築数");

                    b.Property<int>("建築物破壊数");

                    b.Property<TimeSpan>("戦争継続時間");

                    b.Property<int>("戦闘");

                    b.Property<int>("支援");

                    b.Property<string>("攻守");

                    b.Property<int>("結果");

                    b.Property<int>("職業");

                    b.Property<int>("貢献度");

                    b.Property<bool>("集計対象");

                    b.Property<int>("領域");

                    b.Property<int>("領域ダメージボーナス");

                    b.Property<int>("領域破壊ボーナス");

                    b.HasKey("記録日時");

                    b.ToTable("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
